using System.Text.Json.Serialization;

namespace beatleader_songrec.Export;

/// <summary>
/// Root object of a .bplist playlist file.
/// </summary>
public sealed class BplistFile
{
    [JsonPropertyName("playlistTitle")]
    public string PlaylistTitle { get; set; } = string.Empty;

    [JsonPropertyName("playlistAuthor")]
    public string PlaylistAuthor { get; set; } = string.Empty;

    [JsonPropertyName("songs")]
    public List<BplistSong> Songs { get; set; } = [];

    [JsonPropertyName("image")]
    public string? Image { get; set; }

    [JsonPropertyName("customData")]
    public BplistCustomData? CustomData { get; set; }
}

/// <summary>
/// A single song entry within a .bplist playlist.
/// </summary>
public sealed class BplistSong
{
    [JsonPropertyName("hash")]
    public string Hash { get; set; } = string.Empty;

    [JsonPropertyName("key")]
    public string? Key { get; set; }

    [JsonPropertyName("songName")]
    public string SongName { get; set; } = string.Empty;

    [JsonPropertyName("levelAuthorName")]
    public string LevelAuthorName { get; set; } = string.Empty;

    [JsonPropertyName("difficulties")]
    public List<BplistDifficulty> Difficulties { get; set; } = [];
}

/// <summary>
/// A difficulty + characteristic entry for a song within a .bplist playlist.
/// </summary>
public sealed class BplistDifficulty
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("characteristic")]
    public string Characteristic { get; set; } = string.Empty;
}

/// <summary>
/// Custom metadata attached to a .bplist playlist, as generated by BeatLeader.
/// </summary>
public sealed class BplistCustomData
{
    [JsonPropertyName("syncURL")]
    public string? SyncUrl { get; set; }

    [JsonPropertyName("owner")]
    public string? Owner { get; set; }

    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("hash")]
    public string? Hash { get; set; }

    [JsonPropertyName("shared")]
    public bool Shared { get; set; }
}
