using System.Text;
using System.Text.RegularExpressions;

namespace PortableHub;

public sealed record UnitState(string ActiveState, string SubState, int Pid, long? MemoryBytes);

/// <summary>systemd user units for deployments (the hub's user has lingering enabled) and the nginx host maps.</summary>
public sealed partial class HostingService(HubConfig config, ILogger<HostingService> logger)
{
    private const string Systemctl = "/usr/bin/systemctl";
    private readonly SemaphoreSlim _nginxLock = new(1, 1);

    public static string UnitName(string name) => $"portable-{name}.service";
    private static string UnitDir => Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".config", "systemd", "user");

    public string DeploymentDir(string name) => Path.Combine(config.DeploymentsDir, name);
    public string AppLog(string name) => Path.Combine(DeploymentDir(name), "logs", "app.log");

    public async Task WriteUnit(Deployment d)
    {
        var dir = DeploymentDir(d.Name);
        var dll = Path.GetFileNameWithoutExtension(config.ProjectFile) + ".dll";
        var args = string.Join(' ', SplitArgs(d.Args).Select(QuoteForSystemd));
        var unit = $"""
            # generated by portaBLe Hub — edits are overwritten on the next deploy
            [Unit]
            Description=portaBLe {d.Name} ({d.Branch})
            After=network.target

            [Service]
            Type=simple
            WorkingDirectory={dir}/current
            ExecStart={config.Dotnet} {dir}/current/{dll} {args}
            Environment=ASPNETCORE_URLS=http://127.0.0.1:{d.Port}
            Environment=ASPNETCORE_ENVIRONMENT=Production
            Environment=DOTNET_CLI_TELEMETRY_OPTOUT=1
            Environment=DOTNET_gcServer=0
            Environment=Logging__LogLevel__Default=Warning
            StandardOutput=append:{dir}/logs/app.log
            StandardError=append:{dir}/logs/app.log
            Restart=on-failure
            RestartSec=10
            TimeoutStopSec=20
            MemoryMax={config.MemoryMax}

            [Install]
            WantedBy=default.target

            """;
        Directory.CreateDirectory(UnitDir);
        await File.WriteAllTextAsync(Path.Combine(UnitDir, UnitName(d.Name)), unit);
        await Systemd("daemon-reload");
    }

    public async Task RemoveUnit(string name)
    {
        await Shell.Run(Systemctl, ["--user", "disable", "--now", UnitName(name)]);
        File.Delete(Path.Combine(UnitDir, UnitName(name)));
        await Systemd("daemon-reload");
    }

    public Task Systemd(params string[] args) => Shell.Check(Systemctl, ["--user", .. args], timeout: TimeSpan.FromMinutes(2));

    public async Task<UnitState> State(string name)
    {
        var (_, output) = await Shell.Run(Systemctl, ["--user", "show", UnitName(name), "--property=ActiveState,SubState,MainPID,MemoryCurrent"],
            timeout: TimeSpan.FromSeconds(10));
        var props = output.Split('\n', StringSplitOptions.RemoveEmptyEntries).Select(l => l.Split('=', 2)).Where(p => p.Length == 2)
            .ToDictionary(p => p[0], p => p[1].Trim());
        int.TryParse(props.GetValueOrDefault("MainPID"), out var pid);
        long? memory = long.TryParse(props.GetValueOrDefault("MemoryCurrent"), out var m) && m < long.MaxValue / 2 ? m : null;
        if (memory == null && pid > 0) memory = RssFromProc(pid);
        return new UnitState(props.GetValueOrDefault("ActiveState", "unknown"), props.GetValueOrDefault("SubState", ""), pid, memory);
    }

    private static long? RssFromProc(int pid)
    {
        try
        {
            var line = File.ReadLines($"/proc/{pid}/status").FirstOrDefault(l => l.StartsWith("VmRSS:"));
            return line == null ? null : long.Parse(DigitsRegex().Match(line).Value) * 1024;
        }
        catch { return null; }
    }

    /// <summary>Rewrites the host→port and auth maps from the deployments and reloads nginx (rolled back if the config test fails).</summary>
    public async Task WriteNginxMaps(IEnumerable<Deployment> deployments)
    {
        await _nginxLock.WaitAsync();
        try
        {
            Directory.CreateDirectory(config.NginxDir);
            var hosts = new StringBuilder("# generated by portaBLe Hub\n");
            var auth = new StringBuilder("# generated by portaBLe Hub\n");
            foreach (var d in deployments.OrderBy(d => d.Name))
            {
                var host = config.HostFor(d.Name);
                hosts.Append($"{host} {d.Port};\n");
                if (d.Protected) auth.Append($"{host} \"portaBLe {d.Name}\";\n");
            }
            var files = new[] { ("hosts.map", hosts.ToString()), ("auth.map", auth.ToString()) };
            var backups = files.ToDictionary(f => f.Item1, f => File.Exists(Path.Combine(config.NginxDir, f.Item1))
                ? File.ReadAllText(Path.Combine(config.NginxDir, f.Item1)) : null);
            if (files.All(f => backups[f.Item1] == f.Item2)) return;
            foreach (var (file, content) in files) await File.WriteAllTextAsync(Path.Combine(config.NginxDir, file), content);
            var (code, output) = await Shell.Run("/usr/bin/sudo", ["-n", "/usr/sbin/nginx", "-t"]);
            if (code != 0)
            {
                foreach (var (file, old) in backups) await File.WriteAllTextAsync(Path.Combine(config.NginxDir, file), old ?? "");
                throw new InvalidOperationException("nginx config test failed: " + output.Trim());
            }
            await Shell.Check("/usr/bin/sudo", ["-n", "/usr/bin/systemctl", "reload", "nginx"]);
            logger.LogInformation("nginx maps updated");
        }
        finally
        {
            _nginxLock.Release();
        }
    }

    /// <summary>Whitespace-separated arguments; double quotes group words.</summary>
    public static List<string> SplitArgs(string args)
    {
        if (args.Contains('\n') || args.Contains('\r')) throw new ArgumentException("arguments must be on one line");
        return QuotedArgRegex().Matches(args).Select(m => m.Groups[1].Success ? m.Groups[1].Value : m.Groups[2].Value).ToList();
    }

    /// <summary>Quotes one argument for an ExecStart line: systemd specifiers (%) and variables ($) are escaped.</summary>
    private static string QuoteForSystemd(string arg) =>
        "\"" + arg.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("%", "%%").Replace("$", "$$") + "\"";

    [GeneratedRegex("\"([^\"]*)\"|(\\S+)")]
    private static partial Regex QuotedArgRegex();

    [GeneratedRegex(@"\d+")]
    private static partial Regex DigitsRegex();
}
